// Mocks generated by Mockito 5.3.2 from annotations
// in expense_tracker/test/expenditure/expenditure_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:expense_tracker/models/expense_model.dart' as _i5;
import 'package:expense_tracker/models/general_response.dart' as _i2;
import 'package:expense_tracker/repository/expense_repo.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGeneralResponse_0 extends _i1.SmartFake
    implements _i2.GeneralResponse {
  _FakeGeneralResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpenditureRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenditureRepoImpl extends _i1.Mock
    implements _i3.ExpenditureRepoImpl {
  MockExpenditureRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GeneralResponse> addExpenditure({
    required String? category,
    required String? itemName,
    required double? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExpenditure,
          [],
          {
            #category: category,
            #itemName: itemName,
            #amount: amount,
          },
        ),
        returnValue:
            _i4.Future<_i2.GeneralResponse>.value(_FakeGeneralResponse_0(
          this,
          Invocation.method(
            #addExpenditure,
            [],
            {
              #category: category,
              #itemName: itemName,
              #amount: amount,
            },
          ),
        )),
      ) as _i4.Future<_i2.GeneralResponse>);
  @override
  _i4.Future<List<_i5.ExpenditureModel>> getExpenditure() =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenditure,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ExpenditureModel>>.value(
            <_i5.ExpenditureModel>[]),
      ) as _i4.Future<List<_i5.ExpenditureModel>>);
}

/// A class which mocks [GeneralResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeneralResponse extends _i1.Mock implements _i2.GeneralResponse {
  @override
  set message(String? _message) => super.noSuchMethod(
        Invocation.setter(
          #message,
          _message,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set token(String? _token) => super.noSuchMethod(
        Invocation.setter(
          #token,
          _token,
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ExpenditureModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenditureModel extends _i1.Mock implements _i5.ExpenditureModel {
  @override
  set id(String? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set category(String? _category) => super.noSuchMethod(
        Invocation.setter(
          #category,
          _category,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set nameOfItem(String? _nameOfItem) => super.noSuchMethod(
        Invocation.setter(
          #nameOfItem,
          _nameOfItem,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set estimatedAmount(int? _estimatedAmount) => super.noSuchMethod(
        Invocation.setter(
          #estimatedAmount,
          _estimatedAmount,
        ),
        returnValueForMissingStub: null,
      );
}
